sources:
  enchanting:
    chance: 1.0
  chests:
    chance: 0.6
  fishing:
    chance: 0.1
rarities:
  - name: common
    color: green
    weight: 0.55
    minAffixes: 1
    maxAffixes: 1
  - name: uncommon
    color: yellow
    weight: 0.25
    minAffixes: 1
    maxAffixes: 2
  - name: rare
    color: aqua
    weight: 0.12
    enchantable: true
    minAffixes: 1
    maxAffixes: 3
  - name: epic
    color: light_purple
    weight: 0.05
    minAffixes: 2
    maxAffixes: 3
    enchantable: true
  - name: legendary
    color: gold
    weight: 0.02
    minAffixes: 2
    maxAffixes: 4
    enchantable: true
  - name: mythic
    color: red
    weight: 0.01
    minAffixes: 3
    maxAffixes: 5
    enchantable: true
    unbreakable: true