rarities:
  - name: Common
    color: green
    chance: 0.55
  - name: Uncommon
    color: yellow
    chance: 0.25
  - name: Rare
    color: aqua
    chance: 0.12
    enchantable: true
  - name: Epic
    color: light_purple
    chance: 0.05
    enchantable: true
  - name: Legendary
    color: gold
    chance: 0.02
    enchantable: true
  - name: Mythic
    color: red
    chance: 0.01
    enchantable: true
    unbreakable: true