sources:
  enchanting:
    chance: 1.0
  chests:
    chance: 0.6
  fishing:
    chance: 0.1
    luckOfTheSeaBonusChance: 0.021
  drops:
    max: 32
    mobs:
      - type: ELDER_GUARDIAN
        chance: 1.0
        lootingBonusChance: 0.03
      - type: ENDER_DRAGON
        chance: 1.0
        lootingBonusChance: 0.03
      - type: EVOKER
        chance: 1.0
        lootingBonusChance: 0.03
      - type: ILLUSIONER
        chance: 1.0
        lootingBonusChance: 0.03
      - type: GIANT
        chance: 1.0
        lootingBonusChance: 0.03
      - type: WITHER
        chance: 1.0
        lootingBonusChance: 0.03
      - type: WARDEN
        chance: 1.0
        lootingBonusChance: 0.03
      - type: GHAST
        chance: 0.085
      - type: GUARDIAN
        chance: 0.085
      - type: PIGLIN_BRUTE
        chance: 0.085
      - type: RAVAGER
        chance: 0.085
      - type: VEX
        chance: 0.085
      - type: WITHER_SKELETON
        chance: 0.085
      - type: WITCH
        chance: 0.085
      - type: DROWNED
        chance: 0.085
      - type: BLAZE
      - type: CAVE_SPIDER
      - type: CREEPER
      - type: ENDERMAN
      - type: ENDERMITE
      - type: HOGLIN
      - type: HUSK
      - type: MAGMA_CUBE
      - type: PHANTOM
      - type: PIGLIN
      - type: PILLAGER
      - type: SHULKER
      - type: SILVERFISH
      - type: SKELETON
      - type: SLIME
      - type: SPIDER
      - type: STRAY
      - type: VINDICATOR
      - type: ZOGLIN
      - type: ZOMBIE
      - type: ZOMBIE_VILLAGER
      - type: ZOMBIFIED_PIGLIN
rarities:
  - name: common
    color: green
    weight: 0.55
    minAffixes: 1
    maxAffixes: 1
  - name: uncommon
    color: yellow
    weight: 0.25
    minAffixes: 1
    maxAffixes: 2
  - name: rare
    color: aqua
    weight: 0.12
    enchantable: true
    minAffixes: 1
    maxAffixes: 3
  - name: epic
    color: light_purple
    weight: 0.05
    minAffixes: 2
    maxAffixes: 3
    enchantable: true
  - name: legendary
    color: gold
    weight: 0.02
    minAffixes: 2
    maxAffixes: 4
    enchantable: true
  - name: mythic
    color: red
    weight: 0.01
    minAffixes: 3
    maxAffixes: 5
    enchantable: true
    unbreakable: true