name: affixes
version: '1.0-SNAPSHOT'
main: io.github.chasehuegel.affixes.AffixesPlugin
api-version: '1.21'
commands:
  affixes:
    description: Procedural RPG items and affixes.
    usage: /affixes help
    permission: affixes.commands